# Generated by Django 3.0.6 on 2020-05-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
