# Generated by Django 3.0.6 on 2020-05-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200529_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
